services:
  user-api:
    container_name: USER-CRUD
    build: .
    ports:
      - "127.0.0.1:80:5000"
    environment:
      - DATABASE_URI=postgresql://postgres:postgres@127.0.0.1:5432/usr
    depends_on:
      - postgre-db

  postgre-db:
    container_name: DATABASE
    image: postgres:latest
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    volumes:
      - postgre-data:/var/lib/postgresql/data

volumes:
  postgre-data: {}
